timeoutInS:        500
repository:        git@github.com:ipa320/cob_navigation_tests_results
collisionsTopic:   collisions
cameraTopics:      [ /topCamera/image_raw ]

route:
    - [ 0,    0,    0     ]
<<<<<<< HEAD
    - [ 0.5,  0.5,  3.14  ]
    - [ -1,   -1,   0     ]
    - [ 0,    0,    -3.14 ]
=======
    - [ .5,  0.5,  3.14  ]
    - [ -1,   -1,   0     ]
    - [ 0,    0,    -3.14 ]

#setupRobotService: /setup_robot
#robotConfig:
#  arm: folded
#  tray: down

>>>>>>> e26317b93c3972e92fd2615fc5ef0d114e148280
